# Generated by Django 5.2.5 on 2025-08-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('observation', models.CharField(choices=[('smoke', 'Smoke'), ('heat', 'Heat'), ('flames', 'Flames'), ('smell', 'Burning smell'), ('other', 'Other')], max_length=64)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PredictionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('temperature_c', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('wind_speed_ms', models.FloatField(blank=True, null=True)),
                ('rainfall_mm_24h', models.FloatField(blank=True, null=True)),
                ('ndvi', models.FloatField(blank=True, null=True)),
                ('recent_fires', models.IntegerField(default=0)),
                ('risk_score', models.FloatField()),
                ('risk_level', models.CharField(max_length=16)),
            ],
        ),
    ]
