services:
  - type: web
    name: CrisisConnect
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn crisis_communication.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: crisis_communication.settings
      - key: PYTHON_VERSION
        value: 3.10
