services:
  - type: web
    name: CrisisConnect
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn crisis_communication.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: crisis_communication.settings
      - key: PYTHON_VERSION
        value: 3.10
