# Generated by Django 5.0.3 on 2025-07-13 10:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(default='contact@example.com', max_length=254)),
                ('organization', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('emergency_type', models.CharField(choices=[('fire', 'Fire'), ('flood', 'Flood'), ('earthquake', 'Earthquake'), ('medical', 'Medical'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=50)),
                ('phoneNumber', models.CharField(default=' ', max_length=50, validators=[django.core.validators.RegexValidator(message='Only numeric values are allowed', regex='^\\d+$')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='App.forumpost')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(default=' ', max_length=50, validators=[django.core.validators.RegexValidator(message='Only numeric values are allowed', regex='^\\d*$')])),
                ('location', models.CharField(blank=True, default=' ', max_length=100)),
                ('bio', models.TextField(default='Bio information not provided')),
                ('email', models.EmailField(default='example@example.com', max_length=254)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_requested', models.BooleanField(default=False)),
                ('account_type', models.CharField(choices=[('community', 'Community Member'), ('donor', 'Donor/Supporter')], default='community', max_length=50)),
                ('donor_tier', models.CharField(blank=True, choices=[('basic', 'Basic Supporter'), ('standard', 'Standard Donor'), ('premium', 'Premium Supporter')], max_length=50, null=True)),
                ('monthly_contribution', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_donated', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('donor_since', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('Food', 'Food'), ('Water', 'Water'), ('Clothes', 'Clothes'), ('Shelter', 'Shelter'), ('Medical', 'Medical'), ('Transportation', 'Transportation'), ('Tools', 'Tools'), ('Other', 'Other')], max_length=100)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('phoneNumber', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Only numeric values are allowed', regex='^\\d+$')])),
                ('location', models.CharField(max_length=200)),
                ('is_approved', models.BooleanField(default=False)),
                ('date_contributed', models.DateTimeField(auto_now_add=True)),
                ('is_allocated', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResourceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('help_type', models.CharField(choices=[('Food', 'Food'), ('Water', 'Water'), ('Clothes', 'Clothes'), ('Shelter', 'Shelter'), ('Medical', 'Medical'), ('Transportation', 'Transportation'), ('Tools', 'Tools'), ('Other', 'Other')], max_length=100)),
                ('description', models.TextField()),
                ('quantity_requested', models.PositiveIntegerField(default=1)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('fulfilled', 'Fulfilled'), ('rejected', 'Rejected')], default='pending', max_length=50)),
                ('response_message', models.TextField(blank=True, null=True)),
                ('is_fulfilled', models.BooleanField(default=False)),
                ('phoneNumber', models.CharField(default='', max_length=50, validators=[django.core.validators.RegexValidator(message='Only numeric values are allowed', regex='^\\d+$')])),
                ('location', models.CharField(default='', max_length=200)),
                ('matched_contribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
