# Generated by Django 5.0.3 on 2025-07-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='alert_images/'),
        ),
        migrations.AddField(
            model_name='alert',
            name='predicted_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
