# Generated by Django 5.0.3 on 2025-08-09 20:15

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alert_image_alert_predicted_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('report_type', models.CharField(choices=[('fire', 'Fire/Wildfire'), ('illegal_logging', 'Illegal Logging'), ('pollution', 'Pollution'), ('deforestation', 'Deforestation'), ('wildlife_poaching', 'Wildlife Poaching'), ('water_contamination', 'Water Contamination'), ('air_pollution', 'Air Pollution'), ('waste_dumping', 'Illegal Waste Dumping'), ('other', 'Other Environmental Issue')], default='other', max_length=50)),
                ('location_name', models.CharField(help_text='Area/landmark name', max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='report_images/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('verified', 'Verified'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('phoneNumber', models.CharField(default='', max_length=50, validators=[django.core.validators.RegexValidator(message='Enter valid phone number', regex='^\\+?[0-9]{10,15}$')])),
                ('predicted_category', models.CharField(blank=True, max_length=50, null=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
    ]
