# Generated by Django 5.0.3 on 2025-08-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_report_delete_alert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('community', 'Community Member'), ('donor', 'Donor/Supporter'), ('organization', 'Local Organization')], default='community', max_length=50),
        ),
    ]
