# Generated by Django 5.0.3 on 2025-08-10 19:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_profile_account_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreePlanting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Tree Planting Initiative', max_length=250)),
                ('location_name', models.CharField(help_text='Area/location name', max_length=200)),
                ('tree_type', models.CharField(choices=[('indigenous', 'Indigenous Species'), ('exotic', 'Exotic Species'), ('fruit', 'Fruit Trees'), ('bamboo', 'Bamboo'), ('other', 'Other')], default='indigenous', max_length=50)),
                ('number_of_trees', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(help_text='Describe the planting area and purpose')),
                ('before_image', models.ImageField(blank=True, help_text='Photo of area before planting', null=True, upload_to='tree_planting/before/')),
                ('after_image', models.ImageField(blank=True, help_text='Photo after planting trees', null=True, upload_to='tree_planting/after/')),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('planted', 'Planted'), ('verified', 'Verified')], default='planned', max_length=20)),
                ('planted_date', models.DateTimeField(auto_now_add=True)),
                ('phoneNumber', models.CharField(default='', max_length=50, validators=[django.core.validators.RegexValidator(message='Enter valid phone number', regex='^\\+?[0-9]{10,15}$')])),
                ('suitability_score', models.FloatField(blank=True, help_text='Tree survival prediction score', null=True)),
                ('planter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-planted_date'],
            },
        ),
    ]
