# Generated by Django 5.0.3 on 2025-08-12 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='treeplanting',
            name='planter_name',
            field=models.CharField(blank=True, help_text='Name of person who planted (for unregistered users)', max_length=200),
        ),
        migrations.AlterField(
            model_name='treeplanting',
            name='planter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
