# Generated by Django 5.0.3 on 2025-08-12 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_treeplanting_planter_name_alter_treeplanting_planter'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='tree_planting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.treeplanting'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('report_verified', 'Report Verified'), ('report_resolved', 'Report Resolved'), ('tree_verified', 'Tree Planting Verified'), ('general', 'General Notification')], max_length=50),
        ),
    ]
