# Generated by Django 5.0.3 on 2025-08-12 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_notification_tree_planting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='environmental_badges',
            field=models.TextField(blank=True, help_text='Comma-separated list of earned badges'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tree_points',
            field=models.PositiveIntegerField(default=0, help_text='Points from verified tree plantings'),
        ),
        migrations.AddField(
            model_name='treeplanting',
            name='badge_earned',
            field=models.CharField(blank=True, help_text='Badge earned for this planting', max_length=100),
        ),
        migrations.AddField(
            model_name='treeplanting',
            name='reward_points',
            field=models.PositiveIntegerField(default=0, help_text='Points earned for this planting'),
        ),
    ]
