# Generated by Django 5.0.3 on 2025-08-13 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_profile_environmental_badges_profile_tree_points_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('reward_type', models.CharField(choices=[('data_bundle', 'Data Bundle'), ('tree_kit', 'Tree Planting Kit'), ('workshop', 'Workshop Access'), ('certificate', 'Certificate')], max_length=50)),
                ('token_cost', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='treeplanting',
            name='badge_earned',
        ),
        migrations.RemoveField(
            model_name='treeplanting',
            name='reward_points',
        ),
        migrations.AddField(
            model_name='profile',
            name='token_balance',
            field=models.PositiveIntegerField(default=0, help_text='Current token balance'),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_tokens_earned',
            field=models.PositiveIntegerField(default=0, help_text='Total tokens earned all time'),
        ),
        migrations.AddField(
            model_name='treeplanting',
            name='tokens_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('report_photo', 'Environmental Report with Photo'), ('tree_planting', 'Tree Planting Activity'), ('forum_post', 'Community Forum Post'), ('resource_share', 'Resource Sharing')], max_length=50)),
                ('tokens_earned', models.PositiveIntegerField(default=1)),
                ('description', models.CharField(max_length=200)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.report')),
                ('tree_planting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.treeplanting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='UserReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.reward')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
