# Generated by Django 5.0.3 on 2025-08-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_reward_remove_treeplanting_badge_earned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreward',
            name='certificate_url',
            field=models.URLField(blank=True, help_text='URL to generated certificate', null=True),
        ),
    ]
