# Generated by Django 5.0.3 on 2025-08-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_userreward_certificate_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='tokens_awarded',
            field=models.BooleanField(default=False),
        ),
    ]
