# Generated by Django 5.0.3 on 2025-08-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_report_tokens_awarded'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='program_type',
            field=models.CharField(choices=[('environmental', 'Environmental Reporting'), ('trees', '15 Billion Trees Initiative'), ('both', 'Both Programs')], default='both', max_length=20),
        ),
    ]
