# Generated by Django 5.0.3 on 2025-08-16 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_citizenfirereport_fireriskprediction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenfirereport',
            name='reporter_name',
            field=models.CharField(blank=True, help_text='Name for anonymous reports', max_length=200),
        ),
        migrations.AddField(
            model_name='citizenfirereport',
            name='reporter_phone',
            field=models.CharField(blank=True, help_text='Phone for anonymous reports', max_length=50),
        ),
        migrations.AlterField(
            model_name='citizenfirereport',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
