# Generated by Django 5.0.3 on 2025-08-28 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_treeplanting_latitude_treeplanting_longitude'),
    ]

    operations = [
        # This migration is mainly for production (Supabase/PostgreSQL)
        # SQLite doesn't support ALTER CONSTRAINT, so we skip for local dev
    ]
