# Generated by Django 5.0.3 on 2025-08-29 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_auto_20250828_1710'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree_species', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('soil_type', models.CharField(max_length=100)),
                ('rainfall_mm', models.FloatField()),
                ('temperature_c', models.FloatField()),
                ('altitude_m', models.FloatField()),
                ('soil_ph', models.FloatField()),
                ('planting_season', models.CharField(max_length=50)),
                ('planting_method', models.CharField(max_length=100)),
                ('care_level', models.CharField(max_length=50)),
                ('water_source', models.CharField(max_length=100)),
                ('tree_age_months', models.IntegerField()),
                ('survival_probability', models.FloatField(help_text='Probability of survival (0-1)')),
                ('survival_level', models.CharField(choices=[('high', 'High Success Rate'), ('medium', 'Medium Success Rate'), ('low', 'Low Success Rate')], max_length=20)),
                ('recommended_species', models.TextField(blank=True, help_text='JSON list of recommended species')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
