# Generated by Django 5.1.3 on 2024-11-07 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0029_resourcerequest_resource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcerequest',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='resourcerequest',
            name='resource',
        ),
    ]
