# Generated by Django 5.1.3 on 2024-11-12 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0030_remove_resourcerequest_is_approved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='name',
            new_name='Resource_Name',
        ),
    ]
