# Generated by Django 5.1.3 on 2024-11-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0035_resource_is_approved_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
    ]
