# Generated by Django 5.1.3 on 2024-11-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0036_alter_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_namee',
            field=models.CharField(default='', max_length=100),
        ),
    ]
