# Generated by Django 5.1.3 on 2024-11-15 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0038_remove_profile_last_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='last_namee',
            new_name='last_name',
        ),
    ]
