# Generated by Django 5.0.3 on 2025-05-17 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0039_rename_last_namee_profile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
