# Generated by Django 5.0.3 on 2025-05-18 14:47

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0040_remove_comment_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='user',
            new_name='contributor',
        ),
        migrations.AddField(
            model_name='resource',
            name='date_contributed',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resource',
            name='is_allocated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resource',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='resource',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='resource',
            name='phoneNumber',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Only numeric values are allowed', regex='^\\d+$')]),
        ),
    ]
