# Generated by Django 5.0.3 on 2025-05-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0041_rename_user_resource_contributor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='Resource_Name',
        ),
        migrations.AlterField(
            model_name='resource',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('Food', 'Food'), ('Clothes', 'Clothes'), ('Shelter', 'Shelter'), ('Medical', 'Medical')], max_length=100),
        ),
    ]
