# Generated by Django 5.0.3 on 2025-05-18 18:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0042_remove_resource_resource_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcerequest',
            old_name='Resource_type',
            new_name='resource_type',
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='matched_contribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.resource'),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='quantity_requested',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='response_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('fulfilled', 'Fulfilled'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='resourcerequest',
            name='phoneNumber',
            field=models.CharField(default='', max_length=17, validators=[django.core.validators.RegexValidator(message='Only numeric values are allowed', regex='^\\d+$')]),
        ),
    ]
