# Generated by Django 5.0.3 on 2025-05-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0043_rename_resource_type_resourcerequest_resource_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcerequest',
            name='quantity_requested',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='resourcerequest',
            name='resource_type',
            field=models.CharField(choices=[('Food', 'Food'), ('Clothes', 'Clothes'), ('Shelter', 'Shelter'), ('Medical Aid', 'Medical Aid'), ('Water', 'Water'), ('Other', 'Other')], max_length=100),
        ),
    ]
