# Generated by Django 5.0.3 on 2025-05-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0045_profile_is_verified_resource_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verification_requested',
            field=models.BooleanField(default=False),
        ),
    ]
