# Generated by Django 5.0.3 on 2025-05-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0046_profile_verification_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default=' ', max_length=100),
        ),
    ]
