# Generated by Django 5.0.3 on 2025-05-25 11:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0047_alter_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='phoneNumber',
            field=models.CharField(default=' ', max_length=17, validators=[django.core.validators.RegexValidator(message='Only numeric values are allowed', regex='^\\d+$')]),
        ),
    ]
