# Generated by Django 5.0.3 on 2025-05-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0048_alert_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='emergency_type',
            field=models.CharField(choices=[('fire', 'Fire'), ('flood', 'Flood'), ('earthquake', 'Earthquake'), ('medical', 'Medical'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
