# Generated by Django 5.0.3 on 2025-05-25 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0050_rename_resource_type_resourcerequest_help_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='resource_type',
            new_name='help_type',
        ),
    ]
