# Generated by Django 5.0.3 on 2025-07-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0052_rename_help_type_resource_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('Food', 'Food'), ('Water', 'Water'), ('Clothes', 'Clothes'), ('Shelter', 'Shelter'), ('Medical', 'Medical'), ('Transportation', 'Transportation'), ('Tools', 'Tools'), ('Other', 'Other')], max_length=100),
        ),
    ]
