# Generated by Django 5.0.3 on 2025-07-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0053_alter_resource_resource_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcerequest',
            name='help_type',
            field=models.CharField(choices=[('Food', 'Food'), ('Water', 'Water'), ('Clothes', 'Clothes'), ('Shelter', 'Shelter'), ('Medical', 'Medical'), ('Transportation', 'Transportation'), ('Tools', 'Tools'), ('Other', 'Other')], max_length=100),
        ),
    ]
