# Generated by Django 5.0.3 on 2025-07-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0054_alter_resourcerequest_help_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('community', 'Community Member'), ('donor', 'Donor/Supporter')], default='community', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='donor_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='donor_tier',
            field=models.CharField(blank=True, choices=[('basic', 'Basic Supporter - $5/month'), ('standard', 'Standard Donor - $10/month'), ('premium', 'Premium Supporter - $25/month')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='monthly_contribution',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_donated',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
