# Generated by Django 5.0.3 on 2025-07-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0056_alter_profile_donor_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='emergency_type',
            field=models.CharField(choices=[('fire', 'Fire'), ('flood', 'Flood'), ('earthquake', 'Earthquake'), ('medical', 'Medical'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='alert',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=50),
        ),
        migrations.AlterField(
            model_name='emergencycontact',
            name='phone',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('community', 'Community Member'), ('donor', 'Donor/Supporter')], default='community', max_length=50),
        ),
        migrations.AlterField(
            model_name='resource',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='resourcerequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('fulfilled', 'Fulfilled'), ('rejected', 'Rejected')], default='pending', max_length=50),
        ),
    ]
